server:
  port: 9012
spring:
  application:
    name: tensquare_web_zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6060/eureka/
zuul:
  routes:
    tensquare-qa:
      path: /tensquare-qa/**
      serviceId: tensquare-qa
      strip-prefix: false
    tensquare-base:
      path: /tensquare-base/**
      serviceId: tensquare-base
      strip-prefix: false
    tensquare-user:
          path: /tensquare-user/user/**
          serviceId: tensquare-user
          strip-prefix: false
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  sensitive-headers: "*"

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000